name: MacSMPCore
version: '1.0-SNAPSHOT'
main: dev.edwnl.macSMPCore.MacSMPCore
api-version: '1.21'
load: STARTUP

dependencies:
  server:
    PlaceholderAPI:
      # Load order is relative to the dependency. So here PlaceholderAPI loads before our plugin.
      load: BEFORE
      required: false