name: MacSMPCore
version: '1.0'
main: dev.edwnl.macSMPCore.MacSMPCore
api-version: '1.20'
authors:
  - edwnl
depend: [NickAPI]
commands:
  claimchest:
    description: Claims items from the nearest death chest
    usage: /claimchest
    aliases: [cc]
  nick:
    description: Change your nickname
    usage: /nick <name|reset>
  whois:
    description: Reveals the true identity of a nicked player
    usage: /whois <player>